version: '3.8'

services:
  db:
    image: postgres:15
    container_name: matie_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: admin_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: matie_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
